# Generated by Django 5.2.7 on 2025-11-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='status',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='fees',
        ),
    ]
