# Generated by Django 5.2.7 on 2025-11-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_announcement_created_at_alter_announcement_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile',
            field=models.ImageField(default='media/prof.JPG', upload_to='media/'),
        ),
    ]
