# Generated by Django 5.2.7 on 2025-11-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_students_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile',
            field=models.ImageField(default='prof.JPG', upload_to='media/'),
        ),
    ]
