# Generated by Django 5.2.6 on 2025-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='students',
            name='profile',
            field=models.ImageField(default='media/prof.JPG', upload_to='media/'),
        ),
    ]
