# Generated by Django 5.2.6 on 2025-10-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_user_students_user_students_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
